### ISSUE TITLE
Scrub fork-related strings

### ISSUE THREAD

**Issue by markborkum** [pacifica/template-repository#4]
### Pacifica REPLACE_ME version
n/a

### Pacifica Core Software versions
n/a

### Platform Details
n/a

### Scenario:
Modify the initial content of the cloned repository. Replace all "template" strings with clone-specific strings.

### Steps to Reproduce:
n/a

### Expected Result:
All "template" strings should be "pacifica", "template-repository", "pacifica/template-repository", etc.

### Actual Result:
Instance of "dmlb2000" in `README.md` file.

**Comment by dmlb2000** [comment]
The only reference to `dmlb2000` is in the `README.md` and it's referencing a badge which (when rendered) users/developers don't see. Appveyor doesn't seem to have a concept of a project that's not tightly linked with a user account. This is an implementation detail of Appveyor and we can't fix this.

**Comment by dmlb2000** [comment]
I should mention that a possible solution at this time would be to have a QA Team email address to be the primary email address associated with a `pacifica` service account of sorts. Then we could set up group permissions so multiple people could manage the Appveyor pipelines.
